import Head from "next/head";
import Image from "next/image";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "@/lib/query";
import Products from "@/components/Products";
import { Gallery } from "@/styles/Gallery";
import ParentHeroBanner from "@/components/ParentHeroBanner";
import SalesSection from "@/components/SalesSection";
import SalesTitle from "@/components/SalesTitle";

export default function Home() {
  const [result] = useQuery({
    query: PRODUCT_QUERY,
  });
  const { data, fetching, error } = result;

  if (fetching) return <div>Loading...</div>;
  if (error) return <div>Oh no... {error.message}</div>;
  const products = data.products.data;

  return (
    <>
      <Head>
        <title>Botanical Bliss - Plants Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/men-favicon.png" />
      </Head>
      <main>
        <ParentHeroBanner />
        <SalesTitle />
        <SalesSection />
        <Gallery>
          {products.map((product) => (
            <Products key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>
    </>
  );
}
